sudo: required
services:
  - docker

before_install:
  - docker build -t briansamba/docker-react -f Dockerfile.dev .

script: 
  - docker run briansamba/docker-react npm run test -- --coverage
      
